functions:
    - $(find rosplan_stage_waypoint_demo)/scripts/sampling_sensing_functions.py
topics:
    doughnut_visible_from:
        params:
            - '*'
            - '*'
        topic: /update_visibility
        msg_type: std_msgs/String
