turtlebot3_navigation_demo_waypoints:
    # waypoints reference frame
    waypoint_frameid: map

    # waypoint 2D coordinates: x, y, theta
    wp0: [0, 0, -1.57]
    wp1: [2.81, -0.77, -1.57]
    wp2: [-2.24, -1.9, -1.57]
    wp3: [-0.7, 2.3, 1.57]
