turtlebot3_navigation_demo_waypoints:
    # waypoints reference frame
    waypoint_frameid: map

    # waypoint 2D coordinates: x, y, theta
    wp0: [0, 0, 0]
    wp1: [2.81, -1.42, 0]
    wp2: [5.24, -1.94, 0]
    wp3: [4.07, 0.1, 3.1415926]
